name: build-image
run-name: ${{ github.actor }} is building latest image
on: [push]
jobs:
  build_vue_app_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build vue_app image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t yanyue1215/vue_app .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push yanyue1215/vue_app
      - name: build_resume_service
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          cd Backend/    # 后端代码所在目录
          docker build -t yanyue1215/resume_service .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push yanyue1215/resume_service
