name: push-to-private-machine
run-name: ${{ github.actor }} is deploying
on:
  workflow_run:
    workflows:["build-image"] #依赖的工作流程文件的名称
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: remove old container
        run: |
          ssh root@116.204.108.126 "docker ps -a | grep yanyue1215/vue_app | awk '{print $1}' | xargs -r docker rm -f"
          ssh root@116.204.108.126 "docker ps -a | grep yanyue1215/resume_service | awk '{print $1}' | xargs -r docker rm -f"
          ssh root@116.204.108.126 "docker system prune -a"
      - name: pull latest front_image
        run: docker pull yanyue1215/vue_app:latest
      - name: pull latest backend_image
        run: docker pull yanyue1215/resume_service:latest
      - name: Deploy to Virtual Machine
        run: ssh root@116.204.108.126 "cd /root/resume_generator_front && git pull origin master && docker-compose up -d"
